backend

diff --git a/Jenkinsfile.backend b/Jenkinsfile.backend
--- a/Jenkinsfile.backend
+++ b/Jenkinsfile.backend
@@ -11,56 +11,81 @@ pipeline {
 
     stages {
 
-        stage('Build Docker Image') {
-            steps {
-                dir('backend') {
-                    sh '''
-                    sudo docker build -t electronix-backend:${BUILD_NUMBER} .
-                    '''
+        stage('Backend Pipeline') {
+
+            // when {
+            //     changeset "backend/**"
+            // }
+
+            stages {
+
+                stage('Build Docker Image') {
+                    steps {
+                        dir("backend") {
+                            sh '''
+                            sudo docker build -t electronix-backend:${BUILD_NUMBER} .
+                            '''
+                        }
+                    }
                 }
-            }
-        }
 
-        stage('ECR Login') {
-            steps {
-                sh '''
-                sudo aws ecr get-login-password --region ${AWS_REGION} | sudo docker login --username AWS --password-stdin ${ECR_REPO}
-                '''
-            }
-        }
-
-        stage("Tag and Push to ECR") {
-            steps {
-                sh '''
-                sudo docker tag electronix-backend:${BUILD_NUMBER} ${ECR_REPO}:${BUILD_NUMBER}
-                sudo docker tag electronix-backend:${BUILD_NUMBER} ${ECR_REPO}:latest
-
-                sudo docker push ${ECR_REPO}:${BUILD_NUMBER}
-                sudo docker push ${ECR_REPO}:latest
-
-                echo "Pushed Successfully ✅"
-                '''
-            }
-        }
-
-        stage('Deploy to Production') {
-            steps {
-                sshagent(credentials: ['prod-server-ssh-key']) {
-                    sh '''
-                    ssh -o StrictHostKeyChecking=no ubuntu@${PRODUCTION_IP} "echo Connection Success ✅"
-                    '''
+                stage("Test ECR Login") {
+                    steps {
+                        sh '''
+                        aws ecr get-login-password --region ${AWS_REGION} | \
+                        sudo docker login --username AWS --password-stdin ${ECR_REPO}
+                        '''
+                    }
                 }
+
+                stage('Tag & Push ECR') {
+                    steps {
+                        sh '''
+                        sudo docker tag electronix-backend:${BUILD_NUMBER} ${ECR_REPO}:${BUILD_NUMBER}
+                        sudo docker tag electronix-backend:${BUILD_NUMBER} ${ECR_REPO}:latest
+
+                        sudo docker push ${ECR_REPO}:${BUILD_NUMBER}
+                        sudo docker push ${ECR_REPO}:latest
+                        '''
+                    }
+                }
+
+                stage('Deploy To Production') {
+                    steps {
+                        sshagent(['prod-server-ssh-key']){
+                        sh '''
+                        ssh -o StrictHostKeyChecking=no ubuntu@${PRODUCTION_IP} "
+                        aws ecr get-login-password --region ${AWS_REGION} | \
+                        sudo docker login --username AWS --password-stdin ${ECR_REPO} &&
+                        sudo docker pull ${ECR_REPO}:lasets &&
+                        sudo docker stop electronix-backend || true &&
+                        sudo docker rm electronix-backend || true &&
+                        sudo docker run -d --name electronix-backend --env-file /home/ubuntu/.env -p 5000:5000 ${ECR_REPO}:latest
+
+
+                        "
+                        '''  
+                        }
+                    }
+                }
+                stage('Health Check'){
+                    steps{
+                        sh 'sleep 10 && curl -f http://${PRODUCTION_IP}:5000/api/health || exit 1'
+                    }
+                }
+
             }
         }
     }
 
     post {
+
         success {
-            echo "Pipeline completed successfully ✅"
+            echo "ECR login successfully ✅"
         }
 
         failure {
-            echo "Pipeline failed ❌"
+            echo "ECR login Failed ❌"
         }
     }
 }
